export interface UsuarioDto {
    id: number,
    nome: string,
    usuario: string,
    senha: string,
    tipo: number,

    olho: string,
    sobrancelha: string,
    boca: string,
    pele: string,
    chapeu_cabelo: string,
    acessorio: string,
    cor_cabelo: string,
    cor_chapeu: string,
    barba: string,
    cor_barba: string,
    roupa: string,
    cor_roupa: string,
    estampa: string,
}
